spring.application.name=hotel-booking
 
spring.datasource.url=jdbc:postgresql://localhost:5432/HotelRoomBooking
spring.datasource.username=postgres
spring.datasource.password=Admin@1234
 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8081

# JWT configuration 
jwt.secret=ThisIsA32CharLongJwtSecretKeyForHS256
jwt.expiration=3600000
